Neos:
  Neos:
    fusion:
      autoInclude:
        'Webandco.Blog': TRUE
    nodeTypes:
      groups:
        blog:
          position: 200
          label: 'Blog'
    userInterface:
      translation:
        autoInclude:
          Webandco.Blog:
            - 'NodeTypes/*'